### ISSUE TITLE
the readme says it uses MIT license when it's GPL 

### ISSUE THREAD

**Issue by Akane-Kurokawa-1** [3ab3z2/Tic-tac-toe#2]
the [README.md](https://github.com/3ab3z2/Tic-tac-toe/blob/main/README.md) says it uses the MIT license but the [LICENSE](https://github.com/3ab3z2/Tic-tac-toe/blob/main/LICENSE) says it's GPLv3

**Comment by 3ab3z2** [comment]
Edited
